In [1]:
import numpy as np

scores = [72, 85, 90, 63, 88, 55]
scores_array = np.array(scores)

print(scores_array)
print(type(scores_array))
print(scores_array + 5)
print(scores_array * 2)

[72 85 90 63 88 55]
<class 'numpy.ndarray'>
[77 90 95 68 93 60]
[144 170 180 126 176 110]


In [2]:
print(scores_array.mean())
print(scores_array.max())
print(scores_array.min())
print(scores_array.sum())
print(scores_array.std())

passing_mask = scores_array >= 70
print(passing_mask)
print(scores_array[passing_mask])

75.5
90
55
453
13.200378782444085
[ True  True  True False  True False]
[72 85 90 88]


In [5]:
grades_matrix = np.array([
    [72, 85, 90],
    [63, 88, 55],
    [95, 70, 82]
])

print(grades_matrix)
print(grades_matrix.shape)
print(grades_matrix[0])
print(grades_matrix[0,1])
print(grades_matrix[:,0])
print(grades_matrix.mean(axis=0))
print(grades_matrix.mean(axis=1))

[[72 85 90]
 [63 88 55]
 [95 70 82]]
(3, 3)
[72 85 90]
85
[72 63 95]
[76.66666667 81.         75.66666667]
[82.33333333 68.66666667 82.33333333]


In [10]:
#Find the highest single score in the entire matrix, one number, not per row or column
print(grades_matrix.max())
#Find which student, meaning which row index, has the highest average across their three tests
print(np.argmax(grades_matrix.mean(axis=1)))
#Create a boolean mask that flags every individual score below 70, then use it to print just those failing scores as a flat list
failing_scores = grades_matrix < 70
print(grades_matrix[failing_scores])

95
0
[63 55]
